# yaml-language-server: $schema=./build.yaml
name: Build and Deploy
on:
  workflow_dispatch:
  schedule:
  - cron: "0 17 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}      
      - id: rgPresent
        run: |
          if [ "$(az group list --query "[?name=='maxam-dev']" --output tsv)" == "" ]; then
            echo ::set-output name=resourceGroupIsPresent::false
          else
            echo ::set-output name=resourceGroupIsPresent::true
          fi
      - name: Delete ${{ secrets.RESOURCE_GROUP_DEV }}
        if: steps.rgPresent.outputs.resourceGroupIsPresent
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group delete -g ${{ secrets.RESOURCE_GROUP_DEV }} --yes          