# yaml-language-server: $schema=./build.yaml
name: Destroy
on:
  workflow_dispatch:
  schedule:
  - cron: "0 17 * * *"

jobs:
  deploy:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
    
      - name: Delete resources
        uses: azure/powershell@v1
        with:
          azPSVersion: "latest"
          inlineScript: |   
            $rg=Get-AzResourceGroup -name ${{secrets.RESOURCE_GROUP}} -errorAction SilentlyContinue
            if($rg){
              Remove-AzResourceGroup -name ${{secrets.RESOURCE_GROUP}} -Force
            }
            else{
              write-host "Group ${{secrets.RESOURCE_GROUP}} was not found"
            }
            
      - name: Purge APIM
        uses: azure/powershell@v1
        with:
          azPSVersion: "latest"
          inlineScript: |           
            $token = Get-AzAccessToken   
            $headers= @{Authorization = "Bearer $($token.Token)"}         
            $apim = (invoke-restmethod -method GET -uri "https://management.azure.com/subscriptions/${{secrets.AZURE_SUBSCRIPTION_ID}}/providers/Microsoft.ApiManagement/deletedservices?api-version=2021-08-01" -headers $headers).value | select-object id,@{l="resourceid";e={$_.properties.serviceId}}|where-object{$_.resourceId -like "*${{secrets.RESOURCE_GROUP}}*"} 
            if($apim){
              $request = @{
                  Method = 'DELETE'
                  Uri    = "https://management.azure.com$($apim.id)?api-version=2021-08-01"
                  Headers = @{
                      Authorization = "Bearer $($token.Token)"
                  }
              }
              Invoke-RestMethod @request
            }