# yaml-language-server: $schema=./build.yaml
name: Destroy
on:
  workflow_dispatch:
  schedule:
  - cron: "0 17 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}
          enable-AzPSSession: true
    
      - name: Delete resources
        shell: pwsh
        run: |
            $fuckThisShit= Get-AzResourceGroup -name ${{secrets.RESOURCE_GROUP_DEV}}
            if([string]::IsNullOrEmpty($fuckThisShit)){
              write-host "Group ${{secrets.RESOURCE_GROUP_DEV}} was not found"
            }
            else{
              Remove-AzResourceGroup -name ${{secrets.RESOURCE_GROUP_DEV}} -Force
            }
            
      - name: Purge APIM
        uses: azure/powershell@v1
        with:
          azPSVersion: ""
          inlineScript: |           
            $token = Get-AzAccessToken   
            $headers= @{Authorization = "Bearer $($token.Token)"}         
            $apim = (invoke-restmethod --method GET --uri "https://management.azure.com/subscriptions/${{secrets.AZURE_SUBSCRIPTION_ID_DEV}}/providers/Microsoft.ApiManagement/deletedservices?api-version=2021-08-01" -headers $headers).value | select-object id,@{l="resourceid";e={$_.properties.serviceId}}|where-object{$_.resourceId -like "*${{secrets.RESOURCE_GROUP_DEV}}*"} 
            if($apim){
              $request = @{
                  Method = 'DELETE'
                  Uri    = "https://management.azure.com$($apim.id)?api-version=2021-08-01"
                  Headers = @{
                      Authorization = "Bearer $($token.Token)"
                  }
              }
              Invoke-RestMethod @request
            }