# yaml-language-server: $schema=./build.yaml
name: Destroy
on:
  workflow_dispatch:
  schedule:
  - cron: "0 17 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}
          enable-AzPSSession: true
      - name: Check existing resources
        id: rgPresent
        run: |
          if [ "$(az group show --name ${{ secrets.RESOURCE_GROUP_DEV }} --output tsv)" == "" ]; then
            echo ::set-output name=resourceGroupIsPresent::false
            echo ::set-output name=apimIsPresent::false
          else
            echo ::set-output name=resourceGroupIsPresent::true
            if [ "$(az apim list --query "[?name=='${{ secrets.RESOURCE_GROUP_DEV }}']" --output tsv)" == "" ]; then
              echo ::set-output name=apimIsPresent::false
            else
              echo ::set-output name=apimIsPresent::true
            fi
          fi
      - name: Delete resources
        if: steps.rgPresent.outputs.resourceGroupIsPresent
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group delete --name ${{secrets.RESOURCE_GROUP_DEV}} --yes

      - name: Purge APIM
        #if: steps.rgPresent.outputs.apimIsPresent
        uses: azure/powershell@v1
        with:
          azPSVersion: "latest"
          inlineScript: |           
            $token = Get-AzAccessToken   
            $headers= @{Authorization = "Bearer $($token.Token)"}         
            $apim = (invoke-restmethod --method GET --uri "https://management.azure.com/subscriptions/${{secrets.AZURE_SUBSCRIPTION_ID_DEV}}/providers/Microsoft.ApiManagement/deletedservices?api-version=2021-08-01" -headers $headers).value | select-object id,@{l="resourceid";e={$_.properties.serviceId}}|where-object{$_.resourceId -like "*${{secrets.RESOURCE_GROUP_DEV}}*"} 
            $request = @{
                Method = 'DELETE'
                Uri    = "https://management.azure.com$($apim.id)?api-version=2021-08-01"
                Headers = @{
                    Authorization = "Bearer $($token.Token)"
                }
            }
            Invoke-RestMethod @request