# yaml-language-server: $schema=./build.yaml
name: Destroy
on:
  workflow_dispatch:
  schedule:
  - cron: "0 17 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}
      - id: rgPresent
        run: |
          if [ "$(az group show --name ${{ secrets.RESOURCE_GROUP_DEV }} --output tsv)" == "" ]; then
            echo ::set-output name=resourceGroupIsPresent::false
            echo ::set-output name=apimIsPresent::false
          else
            echo ::set-output name=resourceGroupIsPresent::true
            if [ "$(az apim list --query "[?name=='${{ secrets.RESOURCE_GROUP_DEV }}']" --output tsv)" == "" ]; then
              echo ::set-output name=apimIsPresent::false
            else
              echo ::set-output name=apimIsPresent::true
            fi
          fi
      - name: Delete ${{ secrets.RESOURCE_GROUP_DEV }}
        if: steps.rgPresent.outputs.resourceGroupIsPresent
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group delete -g ${{secrets.AZURE_SUBSCRIPTION_ID_DEV}} --yes

      - name: Remove Soft Delete APIM
        if: steps.rgPresent.outputs.apimIsPresent
        uses: azure/CLI@v1
        with:
          inlineScript: |            
            $token = Get-AzAccessToken            
            $apim = (az rest --method GET --url "https://management.azure.com/subscriptions/${{secrets.AZURE_SUBSCRIPTION_ID_DEV}}/providers/Microsoft.ApiManagement/deletedservices?api-version=2021-08-01" --query "value[]" --output json|convertfrom-json)| select-object id,@{l="resourceid";e={$_.properties.serviceId}}|where-object{$_.resourceId -like "*${{secrets.AZURE_SUBSCRIPTION_ID_DEV}}*"} 
            $request = @{
                Method = 'DELETE'
                Uri    = "https://management.azure.com$($apim.id)?api-version=2021-08-01"
                Headers = @{
                    Authorization = "Bearer $($token.Token)"
                }
            }
            Invoke-RestMethod @request