# yaml-language-server: $schema=./build.yaml
name: Build and Deploy
on:
  workflow_call:
    inputs:
      hostname:
        required: false
        type: string
      cname:
        required: false
        type: string
jobs:
  deploy-foundation:
    environment:
      name: production
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy bicep
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create -g maxam-network -l centralus
            az deployment group create -g ${{ secrets.RESOURCE_GROUP }} -f ./deploy/foundation.bicep \
             -p \
                minReplicas=0 \
                nodeImage='${{ needs.build.outputs.containerImage-node }}' \
                nodePort=3000 \
                pythonImage='${{ needs.build.outputs.containerImage-python }}' \
                pythonPort=5000 \
                goImage='${{ needs.build.outputs.containerImage-go }}' \
                goPort=8050 \
                containerRegistry=${{ env.REGISTRY }} \
                containerRegistryUsername=${{ github.actor }} \
                containerRegistryPassword=${{ secrets.PACKAGES_TOKEN }} \
                deployApim=true
